// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhUUcuj2HbBYWVWc4VxDPaAxQXAxWGUsw',
    appId: '1:578932115388:web:6e069e6255a73ecd68cdb9',
    messagingSenderId: '578932115388',
    projectId: 'budget-familial-5c21a',
    authDomain: 'budget-familial-5c21a.firebaseapp.com',
    storageBucket: 'budget-familial-5c21a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgs9WA6vjQudbc5D0Smzlq00jgw3TTol8',
    appId: '1:578932115388:android:d1b5f38388a60ca668cdb9',
    messagingSenderId: '578932115388',
    projectId: 'budget-familial-5c21a',
    storageBucket: 'budget-familial-5c21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFUvyGAHs_esVLACM6hssiYfDDw-kRNmM',
    appId: '1:578932115388:ios:20e9dbb341c3645e68cdb9',
    messagingSenderId: '578932115388',
    projectId: 'budget-familial-5c21a',
    storageBucket: 'budget-familial-5c21a.firebasestorage.app',
    iosBundleId: 'com.example.budgetFamilial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFUvyGAHs_esVLACM6hssiYfDDw-kRNmM',
    appId: '1:578932115388:ios:20e9dbb341c3645e68cdb9',
    messagingSenderId: '578932115388',
    projectId: 'budget-familial-5c21a',
    storageBucket: 'budget-familial-5c21a.firebasestorage.app',
    iosBundleId: 'com.example.budgetFamilial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhUUcuj2HbBYWVWc4VxDPaAxQXAxWGUsw',
    appId: '1:578932115388:web:75f7db8d8cc9780268cdb9',
    messagingSenderId: '578932115388',
    projectId: 'budget-familial-5c21a',
    authDomain: 'budget-familial-5c21a.firebaseapp.com',
    storageBucket: 'budget-familial-5c21a.firebasestorage.app',
  );
}
